book/urls.py
from django.urls import path
from .views import (
    BookListView,
    BookDetailView,
    BookCreateView,
    BookUpdateView,
    BookDeleteView,
)

app_name = 'book'

urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('create/', BookCreateView.as_view(), name='book_create'),
    path('<int:pk>/edit/', BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('book:book_list')),
    path('admin/', admin.site.urls),
    path('books/', include('book.urls')),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models

class Book(models.Model):

    title = models.CharField(max_length=200)
    author = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)
    pages = models.IntegerField()
    price = models.FloatField()
    published_date = models.DateField()

    cover = models.FileField(upload_to='books/', null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)


    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

book/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = [
            'title', 'author', 'description', 'pages', 'price', 
            'published_date', 'cover', 'website', 'email', 'is_published'
        ]
        widgets = {
            'published_date': forms.DateInput(attrs={'type': 'date'}),
        }

book/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.conf import settings
from .models import Book
from .forms import BookForm



class BookListView(ListView):
    model = Book
    template_name = 'book/book_list.html'
    context_object_name = 'page_obj'
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get('q')
        books = Book.objects.all().order_by('-created_at')

        if query:
            books = books.filter(title__icontains=query)

        return books

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context


class BookDetailView(DetailView):
    model = Book
    template_name = 'book/book_detail.html'
    context_object_name = 'book'



class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    template_name = 'book/book_form.html'
    success_url = reverse_lazy('book_list')

    def form_valid(self, form):
        if hasattr(settings, 'HIDE_PRICE') and settings.HIDE_PRICE:
            book = form.save(commit=False)
            book.price = 0
            book.save()
            self.object = book
            return super().form_valid(form)
        else:
            return super().form_valid(form)


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'book/book_form.html'
    success_url = reverse_lazy('book_list')


class BookDeleteView(DeleteView):
    model = Book
    template_name = 'book/book_confirm_delete.html'
    success_url = reverse_lazy('book_list')

templates/book/book_detail.html
<h1>{{ book.title }}</h1>

<p><b>Автор:</b> {{ book.author }}</p>
<p><b>Описание:</b> {{ book.description }}</p>
<p><b>Страниц:</b> {{ book.pages }}</p>
<p><b>Цена:</b> {{ book.price }}</p>
<p><b>Дата публикации:</b> {{ book.published_date }}</p>
<p><b>Просмотров:</b> {{ book.views }}</p>

<a href="{% url 'book:book_list' %}">Назад</a>

templates/book/book_list.html
<h1>Книги</h1>

<form method="get">
    <input type="text" name="q" placeholder="Поиск..." value="{{ query }}">
    <button type="submit">Найти</button>
</form>

<hr>

{% for book in page_obj %}
    <div>
        <h3>
            <a href="{% url 'book:book_detail' book.id %}">
                {{ book.title }}
            </a>
        </h3>
        <p>Автор: {{ book.author }}</p>
        <p>Цена: {{ book.price }}</p>
        <p>Просмотров: {{ book.views }}</p>
    </div>
    <hr>
{% empty %}
    <p>Книги не найдены</p>
{% endfor %}

<div>
    {% if page_obj.has_previous %}
        <a href="?page=1{% if query %}&q={{ query }}{% endif %}">Первая</a>
        <a href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">Назад</a>
    {% endif %}

    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}">Вперед</a>
        <a href="?page={{ page_obj.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">Последняя</a>
    {% endif %}
</div>